### PR TITLE
/v1/models - format output to match OpenAI styling

### PR DESCRIPTION
**Pull request by aricshow**
Adjust /v1/models endpoint so that its output matches the styling of OpenAI's API /v1/models endpoint.
Adjust README.md to state this change, as well as minor edits for clarity between different functions.

### CODE REVIEW

**Comment by Blaizzy** [comment]
@aricshow great job! 🔥

**Comment by Blaizzy** [comment]
Some style checks are failing.

Can you run pre-commit ?

After the tests clear we can merge.

**Comment by aricshow** [comment]
@Blaizzy Oof, sorry, ran and cleared!

**Comment by Blaizzy** [comment]
Could you fix the tests to support your changes

**Pull request merged**
